language: r
r:
  - oldrel
  - release
  - devel

dist: xenial
services:
  - xvfb

before_install:
  - sudo apt-get install -y mesa-common-dev libglu1-mesa-dev libmagick++-dev

r_packages:
  - covr

script:
- travis_wait 15 R CMD build .
- travis_wait 50 R CMD check *tar.gz

after_success:
  - Rscript -e 'library(covr); codecov(type = "all")'
